version: "3"
services:
  server:
    image: yazidi112/spring-mysql-jwt
    ports:
      - "8080:8080"
    environment:
      - spring.datasource.url=jdbc:mysql://mysqldb:3306/user_management?useSSL=false
    networks:
      - springmysql-net
    depends_on:
      - mysqldb

  mysqldb:
    image: mysql:5.7
    networks:
      - springmysql-net
    environment:
      - MYSQL_ROOT_PASSWORD=1234
      - MYSQL_DATABASE=user_management
      - MYSQL_USER=hamid
      - MYSQL_PASSWORD=hamid

networks:
  springmysql-net:
